### ISSUE TITLE
Composer Failing: Failed to download psr/clock from dist: curl error

### ISSUE THREAD

**Issue by neilmillard** [php-fig/clock#15]
Failed to download psr/clock from dist: curl error 28 while downloading https://api.github.com/repos/php-fig/clock/zipball/e41a24703d4560fd0acb709162f73b8adfc3aa0d: SSL connection timeout

It could be API limits (https://github.com/composer/composer/issues/8710) or LFS (https://github.com/microsoft/powerplatform-actions/issues/416)

**Comment by neilmillard** [comment]
Possible workaround is to add Oauth token.
As I'm building from docker
```Dockerfile
# pass OAuth token as a docker build argument
ARG GITHUB_OAUTH
# configure token
RUN composer config -g github-oauth.github.com $GITHUB_OAUTH
```
or

However, it seems like setting the GitHub token directly in the composer.json works:
```yaml
"config": {
    "github-oauth": {
        "github.com": "XXXXXXXXXXXXXXXXXXXXXX"
    }
},
```

Using GitHub token authentication
